



# PROPAGATION_DELAY = 10
# TRANSMISSION_DELAY = 0
# PROCESSING_DELAY = 2

INGRESS_LOC = 10
BUFF_SIZE = []
TOTAL_CAPACITY_ISP = 10000



WINDOW_COUNTER = 0
DEFENSE_TYPE = "dynamic"
WINDOW_COUNTER = 0


TCP_SYN_DETECT_ACCURACY = 0.9
UDP_DETECT_ACCURACY = 0.9
#BUFFER_SIZE
# #-----QUEUING_DELAY = PROCESSING_DELAY*NUM_PKTS_IN_QUEUE



PREV_TRAFFIC_STATS = []
CURR_TRAFFIC_STATS = []
PEAK_TRAFFIC = []
MIN_TRAFFIC = []
CAPACITY = []

# UDP_DETECTION = 0.9

receiveCounter = [0] * INGRESS_LOC
legitimateDropCounter = [0] * INGRESS_LOC
processCounter = [0] * INGRESS_LOC